"""Report generation engine supporting PDF, HTML, Markdown, JSON."""
import json
from datetime import datetime, timezone
from pathlib import Path
from dataclasses import dataclass

from jinja2 import Environment, BaseLoader


@dataclass
class ReportConfig:
    title: str = "Penetration Test Report"
    author: str = "Arcanum Core"
    company: str = ""
    classification: str = "CONFIDENTIAL"
    include_executive_summary: bool = True
    include_methodology: bool = True
    include_findings: bool = True
    include_remediation: bool = True
    include_appendix: bool = True


REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ config.title }}</title>
<style>
  :root { --critical: #dc2626; --high: #ea580c; --medium: #ca8a04; --low: #2563eb; --info: #6b7280; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a2e; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 40px 20px; }
  h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #0f0f23; }
  h2 { font-size: 1.5rem; margin: 2rem 0 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #e5e7eb; }
  h3 { font-size: 1.2rem; margin: 1.5rem 0 0.5rem; }
  .header { text-align: center; margin-bottom: 3rem; padding: 2rem; background: linear-gradient(135deg, #0f0f23, #1a1a3e); color: white; border-radius: 12px; }
  .header h1 { color: white; font-size: 2.5rem; }
  .header .meta { color: #94a3b8; margin-top: 1rem; }
  .classification { display: inline-block; padding: 4px 12px; background: #dc2626; color: white; font-weight: bold; border-radius: 4px; font-size: 0.8rem; }
  .summary-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
  .card { padding: 1.5rem; border-radius: 8px; text-align: center; color: white; }
  .card.critical { background: var(--critical); }
  .card.high { background: var(--high); }
  .card.medium { background: var(--medium); }
  .card.low { background: var(--low); }
  .card .count { font-size: 2rem; font-weight: bold; }
  .card .label { font-size: 0.85rem; opacity: 0.9; }
  .finding { border: 1px solid #e5e7eb; border-radius: 8px; margin: 1rem 0; padding: 1.5rem; border-left: 4px solid; }
  .finding.critical { border-left-color: var(--critical); }
  .finding.high { border-left-color: var(--high); }
  .finding.medium { border-left-color: var(--medium); }
  .finding.low { border-left-color: var(--low); }
  .finding .severity { display: inline-block; padding: 2px 8px; border-radius: 4px; color: white; font-size: 0.75rem; font-weight: bold; }
  .finding .severity.critical { background: var(--critical); }
  .finding .severity.high { background: var(--high); }
  .finding .severity.medium { background: var(--medium); }
  .finding .severity.low { background: var(--low); }
  .finding .title { font-size: 1.1rem; font-weight: 600; margin: 0.5rem 0; }
  .evidence { background: #f8fafc; padding: 1rem; border-radius: 4px; margin: 0.5rem 0; }
  pre { background: #1e1e2e; color: #cdd6f4; padding: 1rem; border-radius: 6px; overflow-x: auto; font-size: 0.85rem; }
  code { font-family: 'JetBrains Mono', 'Fira Code', monospace; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
  th { background: #f1f5f9; font-weight: 600; }
  .footer { text-align: center; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.85rem; }
</style>
</head>
<body>

<div class="header">
  <div class="classification">{{ config.classification }}</div>
  <h1>{{ config.title }}</h1>
  <div class="meta">
    <p>Generated by {{ config.author }} | {{ generated_at }}</p>
    <p>Target: {{ session.target }} | Operation: {{ session.name }}</p>
  </div>
</div>

{% if config.include_executive_summary %}
<h2>1. Executive Summary</h2>
<p>This report presents the findings from the security assessment of <strong>{{ session.target }}</strong>.
The assessment was conducted using Arcanum Core in <strong>{{ session.mode }}</strong> mode.</p>

<div class="summary-cards">
  <div class="card critical"><div class="count">{{ counts.critical }}</div><div class="label">Critical</div></div>
  <div class="card high"><div class="count">{{ counts.high }}</div><div class="label">High</div></div>
  <div class="card medium"><div class="count">{{ counts.medium }}</div><div class="label">Medium</div></div>
  <div class="card low"><div class="count">{{ counts.low }}</div><div class="label">Low</div></div>
</div>
{% endif %}

{% if config.include_findings %}
<h2>2. Findings</h2>

<table>
<thead><tr><th>#</th><th>Severity</th><th>Title</th><th>CVSS</th><th>Status</th></tr></thead>
<tbody>
{% for f in findings %}
<tr>
  <td>{{ loop.index }}</td>
  <td><span class="severity {{ f.severity }}">{{ f.severity | upper }}</span></td>
  <td>{{ f.title }}</td>
  <td>{{ f.cvss_score or 'N/A' }}</td>
  <td>{{ 'Verified' if f.verified else 'Unverified' }}</td>
</tr>
{% endfor %}
</tbody>
</table>

<h2>3. Detailed Findings</h2>

{% for f in findings %}
<div class="finding {{ f.severity }}">
  <span class="severity {{ f.severity }}">{{ f.severity | upper }}</span>
  <span style="color:#6b7280;margin-left:0.5rem;">CVSS: {{ f.cvss_score or 'N/A' }}</span>
  <div class="title">{{ f.title }}</div>

  {% if f.affected %}
  <div class="evidence">
    <strong>Affected:</strong> {{ f.affected.get('method', '') }} {{ f.affected.get('url', '') }}
    {% if f.affected.get('parameter') %} (Parameter: {{ f.affected.parameter }}){% endif %}
  </div>
  {% endif %}

  {% if f.evidence %}
  <h4>Evidence</h4>
  {% if f.evidence.get('request') %}<pre><code>{{ f.evidence.request }}</code></pre>{% endif %}
  {% if f.evidence.get('response') %}<pre><code>{{ f.evidence.response[:500] }}</code></pre>{% endif %}
  {% endif %}

  {% if f.poc %}
  <h4>Proof of Concept</h4>
  {% if f.poc.get('command') %}<pre><code>{{ f.poc.command }}</code></pre>{% endif %}
  {% endif %}

  {% if f.remediation %}
  <h4>Remediation</h4>
  <p>{{ f.remediation }}</p>
  {% endif %}
</div>
{% endfor %}
{% endif %}

{% if config.include_remediation %}
<h2>4. Remediation Roadmap</h2>
<table>
<thead><tr><th>Priority</th><th>Finding</th><th>Recommendation</th></tr></thead>
<tbody>
{% for f in findings %}
<tr>
  <td><span class="severity {{ f.severity }}">{{ f.severity | upper }}</span></td>
  <td>{{ f.title }}</td>
  <td>{{ f.remediation or 'See detailed finding' }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

<div class="footer">
  <p>Generated by Arcanum Core v3.0.0 | {{ generated_at }}</p>
  <p>This document is {{ config.classification }}</p>
</div>

</body>
</html>"""


REPORT_MD_TEMPLATE = """# {{ config.title }}

**Classification:** {{ config.classification }}
**Generated:** {{ generated_at }}
**Target:** {{ session.target }}
**Operation:** {{ session.name }}
**Mode:** {{ session.mode }}

---

## Executive Summary

| Severity | Count |
|----------|-------|
| Critical | {{ counts.critical }} |
| High | {{ counts.high }} |
| Medium | {{ counts.medium }} |
| Low | {{ counts.low }} |

**Total Findings:** {{ findings | length }}

---

## Findings Summary

| # | Severity | Title | CVSS | Status |
|---|----------|-------|------|--------|
{% for f in findings %}| {{ loop.index }} | {{ f.severity | upper }} | {{ f.title }} | {{ f.cvss_score or 'N/A' }} | {{ 'Verified' if f.verified else 'Unverified' }} |
{% endfor %}

---

## Detailed Findings

{% for f in findings %}
### {{ loop.index }}. {{ f.title }}

- **Severity:** {{ f.severity | upper }}
- **CVSS Score:** {{ f.cvss_score or 'N/A' }}
{% if f.cvss_vector %}- **CVSS Vector:** {{ f.cvss_vector }}{% endif %}
{% if f.affected %}- **Affected:** {{ f.affected.get('method', '') }} {{ f.affected.get('url', '') }}{% endif %}
{% if f.cve_id %}- **CVE:** {{ f.cve_id }}{% endif %}

{% if f.evidence and f.evidence.get('request') %}
**Request:**
```
{{ f.evidence.request }}
```
{% endif %}

{% if f.poc and f.poc.get('command') %}
**Proof of Concept:**
```bash
{{ f.poc.command }}
```
{% endif %}

{% if f.remediation %}
**Remediation:** {{ f.remediation }}
{% endif %}

---
{% endfor %}

## Remediation Roadmap

| Priority | Finding | Recommendation |
|----------|---------|----------------|
{% for f in findings %}| {{ f.severity | upper }} | {{ f.title }} | {{ f.remediation or 'See finding details' }} |
{% endfor %}

---

*Generated by Arcanum Core v3.0.0*
"""


class ReportEngine:
    """Generates security assessment reports in multiple formats."""

    def __init__(self):
        self.env = Environment(loader=BaseLoader(), autoescape=False)
        self.html_template = self.env.from_string(REPORT_HTML_TEMPLATE)
        self.md_template = self.env.from_string(REPORT_MD_TEMPLATE)

    def _prepare_context(self, session: dict, findings: list[dict], config: ReportConfig) -> dict:
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in findings:
            sev = (f.get("severity") or "info").lower()
            if sev in counts:
                counts[sev] += 1
        # Sort findings by severity
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        findings_sorted = sorted(findings, key=lambda f: severity_order.get((f.get("severity") or "info").lower(), 5))
        return {
            "config": config,
            "session": session,
            "findings": findings_sorted,
            "counts": counts,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        }

    def generate_html(self, session: dict, findings: list[dict], config: ReportConfig = None) -> str:
        config = config or ReportConfig()
        ctx = self._prepare_context(session, findings, config)
        return self.html_template.render(**ctx)

    def generate_markdown(self, session: dict, findings: list[dict], config: ReportConfig = None) -> str:
        config = config or ReportConfig()
        ctx = self._prepare_context(session, findings, config)
        return self.md_template.render(**ctx)

    def generate_json(self, session: dict, findings: list[dict], config: ReportConfig = None) -> str:
        config = config or ReportConfig()
        return json.dumps({
            "report": {
                "title": config.title,
                "classification": config.classification,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "author": config.author,
            },
            "session": session,
            "summary": {
                "total": len(findings),
                "critical": sum(1 for f in findings if f.get("severity") == "critical"),
                "high": sum(1 for f in findings if f.get("severity") == "high"),
                "medium": sum(1 for f in findings if f.get("severity") == "medium"),
                "low": sum(1 for f in findings if f.get("severity") == "low"),
            },
            "findings": findings,
        }, indent=2)

    def generate_pdf(self, session: dict, findings: list[dict], output_path: Path, config: ReportConfig = None) -> Path:
        """Generate PDF report using WeasyPrint."""
        html_content = self.generate_html(session, findings, config)
        try:
            from weasyprint import HTML
            HTML(string=html_content).write_pdf(str(output_path))
        except ImportError:
            # Fallback: save as HTML if WeasyPrint not available
            output_path = output_path.with_suffix(".html")
            output_path.write_text(html_content)
        return output_path

    async def export(self, session: dict, findings: list[dict], output_dir: Path,
                     formats: list[str] = None, config: ReportConfig = None) -> dict[str, Path]:
        """Export report in multiple formats."""
        formats = formats or ["html", "json", "md"]
        config = config or ReportConfig()
        output_dir.mkdir(parents=True, exist_ok=True)
        base_name = f"report-{session.get('name', 'unknown')}-{datetime.now(timezone.utc).strftime('%Y%m%d')}"
        results = {}

        if "html" in formats:
            path = output_dir / f"{base_name}.html"
            path.write_text(self.generate_html(session, findings, config))
            results["html"] = path

        if "md" in formats:
            path = output_dir / f"{base_name}.md"
            path.write_text(self.generate_markdown(session, findings, config))
            results["md"] = path

        if "json" in formats:
            path = output_dir / f"{base_name}.json"
            path.write_text(self.generate_json(session, findings, config))
            results["json"] = path

        if "pdf" in formats:
            path = output_dir / f"{base_name}.pdf"
            results["pdf"] = self.generate_pdf(session, findings, path, config)

        return results
